// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>
#include <csharp/interfaces.h>
#include <csharp/primitives.h>

// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

#include "InstrInfo.h"
#include <string>
#include <vector>
#include <csharp/exceptionhelper.h>

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
using namespace Iced::Intel::FormatterInternal;
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::GasFormatterInternal
{
	class InstrInfos final
	{
	public:
		static std::vector<InstrInfo*> AllInfos;
	private:
		static std::string AddSuffix(const std::string& s, std::vector<char>& ca);
		static std::string AddPrefix(const std::string& s, std::vector<char>& ca);
		static std::vector<InstrInfo*> ReadInfos();


		static std::vector<std::uint8_t> GetSerializedInstrInfos();
	};
}
