// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>
#include <csharp/interfaces.h>
#include <csharp/primitives.h>

// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

#include <vector>

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::InstructionInfoInternal
{
	class RflagsInfoConstants final
	{
	public:
		static std::vector<std::uint16_t> flagsRead;
		static std::vector<std::uint16_t> flagsUndefined;
		static std::vector<std::uint16_t> flagsWritten;
		static std::vector<std::uint16_t> flagsCleared;
		static std::vector<std::uint16_t> flagsSet;
		static std::vector<std::uint16_t> flagsModified;
	};
}
