// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>



// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::NasmFormatterInternal
{
	enum class BranchSizeInfo
	{
		None,
		Near,
		NearWord,
		NearDword,
		Word,
		Dword,
		Short
	};

	DEFINE_COMP(BranchSizeInfo)
		DEFINE_ARITH(BranchSizeInfo)

}
