// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>



// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::NasmFormatterInternal
{
	enum class InstrOpInfoFlags : std::uint32_t
	{
		None = 0x00000000,
		MemSize_Nothing = 0x00000001,
		ShowNoMemSize_ForceSize = 0x00000002,
		ShowMinMemSize_ForceSize = 0x00000004,
		SizeOverrideMask = 0x00000003,
		OpSizeShift = 0x00000003,
		OpSize16 = 0x00000008,
		OpSize32 = 0x00000010,
		OpSize64 = 0x00000018,
		AddrSizeShift = 0x00000005,
		AddrSize16 = 0x00000020,
		AddrSize32 = 0x00000040,
		AddrSize64 = 0x00000060,
		BranchSizeInfoShift = 0x00000007,
		BranchSizeInfoMask = 0x00000007,
		BranchSizeInfo_Short = 0x00000300,
		SignExtendInfoShift = 0x0000000A,
		SignExtendInfoMask = 0x00000007,
		MemorySizeInfoShift = 0x0000000D,
		MemorySizeInfoMask = 0x00000003,
		FarMemorySizeInfoShift = 0x0000000F,
		FarMemorySizeInfoMask = 0x00000003,
		RegisterTo = 0x00020000,
		BndPrefix = 0x00040000,
		MnemonicIsDirective = 0x00080000,
		JccNotTaken = 0x00100000,
		JccTaken = 0x00200000,
		MemorySizeBits = 0x00000008,
		MemorySizeShift = 0x00000016,
		MemorySizeMask = 0x000000FF
	};
	DEFINE_FLAGS(InstrOpInfoFlags)
		DEFINE_COMP(InstrOpInfoFlags)
		DEFINE_ARITH(InstrOpInfoFlags)

}
