/* 
SPDX-License-Identifier: MIT
Copyright (C) 2018-present iced project and contributors
 */

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#if defined(NASM)
#include <array>
#include <cstdint>
#include <stdexcept>
#include <string>
#include "../ToString.h"
#include "../Internal/StringHelpers.h"
namespace Iced::Intel::NasmFormatterInternal {
	enum class InstrOpInfoFlags : std::uint32_t {
		None  = 0x00000000,
		MemSize_Nothing  = 0x00000001,
		ShowNoMemSize_ForceSize  = 0x00000002,
		ShowMinMemSize_ForceSize  = 0x00000004,
		SizeOverrideMask  = 0x00000003,
		OpSizeShift  = 0x00000003,
		OpSize16  = 0x00000008,
		OpSize32  = 0x00000010,
		OpSize64  = 0x00000018,
		AddrSizeShift  = 0x00000005,
		AddrSize16  = 0x00000020,
		AddrSize32  = 0x00000040,
		AddrSize64  = 0x00000060,
		BranchSizeInfoShift  = 0x00000007,
		BranchSizeInfoMask  = 0x00000007,
		BranchSizeInfo_Short  = 0x00000300,
		SignExtendInfoShift  = 0x0000000A,
		SignExtendInfoMask  = 0x00000007,
		MemorySizeInfoShift  = 0x0000000D,
		MemorySizeInfoMask  = 0x00000003,
		FarMemorySizeInfoShift  = 0x0000000F,
		FarMemorySizeInfoMask  = 0x00000003,
		RegisterTo  = 0x00020000,
		BndPrefix  = 0x00040000,
		MnemonicIsDirective  = 0x00080000,
		JccNotTaken  = 0x00100000,
		JccTaken  = 0x00200000,
		MemorySizeBits  = 0x00000008,
		MemorySizeShift  = 0x00000016,
		MemorySizeMask  = 0x000000FF,
	};
	constexpr InstrOpInfoFlags& operator^=(InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return a = (InstrOpInfoFlags)((std::uint32_t)a ^ (std::uint32_t)b); }
	constexpr InstrOpInfoFlags operator^(const InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return (InstrOpInfoFlags)((std::uint32_t)a ^ (std::uint32_t)b); }
	constexpr InstrOpInfoFlags& operator|=(InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return a = (InstrOpInfoFlags)((std::uint32_t)a | (std::uint32_t)b); }
	constexpr InstrOpInfoFlags operator|(const InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return (InstrOpInfoFlags)((std::uint32_t)a | (std::uint32_t)b); }
	constexpr InstrOpInfoFlags& operator&=(InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return a = (InstrOpInfoFlags)((std::uint32_t)a & (std::uint32_t)b); }
	constexpr InstrOpInfoFlags operator&(const InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return (InstrOpInfoFlags)((std::uint32_t)a & (std::uint32_t)b); }
	constexpr InstrOpInfoFlags operator~(const InstrOpInfoFlags& a) { return (InstrOpInfoFlags)(~((std::uint32_t)a)); }
	constexpr std::uint32_t operator+(const InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return ((std::uint32_t)a + (std::uint32_t)b); }
	constexpr std::uint32_t operator+(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a + b); }
	constexpr std::uint32_t operator+(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a + (std::uint32_t)b); }
	constexpr std::uint32_t operator-(const InstrOpInfoFlags& a, const InstrOpInfoFlags& b) { return ((std::uint32_t)a - (std::uint32_t)b); }
	constexpr std::uint32_t operator-(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a - b); }
	constexpr std::uint32_t operator-(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a - (std::uint32_t)b); }
	constexpr InstrOpInfoFlags operator++(InstrOpInfoFlags& a, int) { auto temp = a; a = InstrOpInfoFlags(a + 1); return temp; }
	constexpr InstrOpInfoFlags& operator++(InstrOpInfoFlags& a) { return a = InstrOpInfoFlags(a + 1); }
	constexpr InstrOpInfoFlags operator--(InstrOpInfoFlags& a, int) { auto temp = a; a = InstrOpInfoFlags(a - 1); return temp; }
	constexpr InstrOpInfoFlags& operator--(InstrOpInfoFlags& a) { return a = InstrOpInfoFlags(a - 1); }
	constexpr bool operator==(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a == b); }
	constexpr bool operator==(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a == (std::uint32_t)b); }
	constexpr bool operator>=(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a >= b); }
	constexpr bool operator>=(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a >= (std::uint32_t)b); }
	constexpr bool operator<=(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a <= b); }
	constexpr bool operator<=(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a <= (std::uint32_t)b); }
	constexpr bool operator>(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a > b); }
	constexpr bool operator>(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a > (std::uint32_t)b); }
	constexpr bool operator<(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a < b); }
	constexpr bool operator<(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a < (std::uint32_t)b); }
	constexpr bool operator!=(const InstrOpInfoFlags& a, const std::uint32_t& b) { return ((std::uint32_t)a != b); }
	constexpr bool operator!=(const std::uint32_t& a, const InstrOpInfoFlags& b) { return (a != (std::uint32_t)b); }
}
template <>
constexpr std::string Iced::Intel::ToString(const Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags& e) {
	std::string result;
	auto temp = e;
	if (temp == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::None) {
		return "None";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeMask;
		result += "MemorySizeMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoShift;
		result += "FarMemorySizeInfoShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoShift;
		result += "BranchSizeInfoShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfoMask;
		result += "BranchSizeInfoMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoMask;
		result += "SignExtendInfoMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoShift;
		result += "MemorySizeInfoShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeShift;
		result += "MemorySizeShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SizeOverrideMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SizeOverrideMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SizeOverrideMask;
		result += "SizeOverrideMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSizeShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSizeShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSizeShift;
		result += "OpSizeShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeInfoMask;
		result += "MemorySizeInfoMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoMask) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoMask) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::FarMemorySizeInfoMask;
		result += "FarMemorySizeInfoMask, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSizeShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSizeShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSizeShift;
		result += "AddrSizeShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoShift) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoShift) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::SignExtendInfoShift;
		result += "SignExtendInfoShift, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize64) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize64) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize64;
		result += "OpSize64, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize64) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize64) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize64;
		result += "AddrSize64, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfo_Short) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfo_Short) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BranchSizeInfo_Short;
		result += "BranchSizeInfo_Short, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemSize_Nothing) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemSize_Nothing) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemSize_Nothing;
		result += "MemSize_Nothing, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowNoMemSize_ForceSize) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowNoMemSize_ForceSize) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowNoMemSize_ForceSize;
		result += "ShowNoMemSize_ForceSize, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowMinMemSize_ForceSize) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowMinMemSize_ForceSize) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::ShowMinMemSize_ForceSize;
		result += "ShowMinMemSize_ForceSize, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize16) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize16) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize16;
		result += "OpSize16, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeBits) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeBits) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MemorySizeBits;
		result += "MemorySizeBits, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize32) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize32) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::OpSize32;
		result += "OpSize32, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize16) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize16) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize16;
		result += "AddrSize16, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize32) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize32) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::AddrSize32;
		result += "AddrSize32, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::RegisterTo) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::RegisterTo) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::RegisterTo;
		result += "RegisterTo, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BndPrefix) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BndPrefix) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::BndPrefix;
		result += "BndPrefix, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MnemonicIsDirective) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MnemonicIsDirective) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::MnemonicIsDirective;
		result += "MnemonicIsDirective, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccNotTaken) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccNotTaken) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccNotTaken;
		result += "JccNotTaken, ";
	}
	if ((temp & Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccTaken) == Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccTaken) {
		temp ^= Iced::Intel::NasmFormatterInternal::InstrOpInfoFlags::JccTaken;
		result += "JccTaken, ";
	}
	if (temp != 0 || result.empty()) return Internal::StringHelpers::ToDec((std::uint32_t)e);
	return result.substr(0, result.size() - 2);
}
#endif
