// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>
#include <csharp/interfaces.h>
#include <csharp/primitives.h>

// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::FastFormatterInternal
{
	enum class FastFmtFlags : std::uint8_t
	{
		None = 0x00000000,
		HasVPrefix = 0x00000001,
		SameAsPrev = 0x00000002,
		ForceMemSize = 0x00000004,
		PseudoOpsKindShift = 0x00000003,
		cmpps = 0x00000008,
		vcmpps = 0x00000010,
		cmppd = 0x00000018,
		vcmppd = 0x00000020,
		cmpss = 0x00000028,
		vcmpss = 0x00000030,
		cmpsd = 0x00000038,
		vcmpsd = 0x00000040,
		pclmulqdq = 0x00000048,
		vpclmulqdq = 0x00000050,
		vpcomb = 0x00000058,
		vpcomw = 0x00000060,
		vpcomd = 0x00000068,
		vpcomq = 0x00000070,
		vpcomub = 0x00000078,
		vpcomuw = 0x00000080,
		vpcomud = 0x00000088,
		vpcomuq = 0x00000090,
		vpcmpb = 0x00000098,
		vpcmpw = 0x000000A0,
		vpcmpd = 0x000000A8,
		vpcmpq = 0x000000B0,
		vpcmpub = 0x000000B8,
		vpcmpuw = 0x000000C0,
		vpcmpud = 0x000000C8,
		vpcmpuq = 0x000000D0,
		vcmpph = 0x000000D8,
		vcmpsh = 0x000000E0,
		vcmpps8 = 0x000000E8,
		vcmppd8 = 0x000000F0,
		vpcmpd6 = 0x000000F8
	};
	DEFINE_FLAGS(FastFmtFlags)
		DEFINE_COMP(FastFmtFlags)
		DEFINE_ARITH(FastFmtFlags)

}
