// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>
#include <csharp/interfaces.h>
#include <csharp/primitives.h>

// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel::DecoderInternal
{
	enum class LegacyHandlerFlags : uint
	{
		HandlerReg = 0x00000001,
		HandlerMem = 0x00000002,
		Handler66Reg = 0x00000004,
		Handler66Mem = 0x00000008,
		HandlerF3Reg = 0x00000010,
		HandlerF3Mem = 0x00000020,
		HandlerF2Reg = 0x00000040,
		HandlerF2Mem = 0x00000080
	};
	DEFINE_FLAGS(LegacyHandlerFlags)
		DEFINE_COMP(LegacyHandlerFlags)
		DEFINE_ARITH(LegacyHandlerFlags)

}
