// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>



// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel
{
	/// <summary>(MVEX) EH bit value</summary>
	enum class MvexEHBit
	{
		/// <summary>Not hard coded to 0 or 1 so can be used for other purposes</summary>
		None = 0,
		/// <summary>EH bit must be 0</summary>
		EH0 = 1,
		/// <summary>EH bit must be 1</summary>
		EH1 = 2
	};

	DEFINE_COMP(MvexEHBit)
		DEFINE_ARITH(MvexEHBit)

}
