// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>
#include <csharp/interfaces.h>
#include <csharp/primitives.h>

// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel
{
	/// <summary><c>RFLAGS</c> bits, FPU condition code bits and misc bits (<c>UIF</c>) supported by the instruction info code</summary>
	enum class RflagsBits
	{
		/// <summary>No bit is set</summary>
		None = 0x00000000,
		/// <summary><c>RFLAGS.OF</c></summary>
		OF = 0x00000001,
		/// <summary><c>RFLAGS.SF</c></summary>
		SF = 0x00000002,
		/// <summary><c>RFLAGS.ZF</c></summary>
		ZF = 0x00000004,
		/// <summary><c>RFLAGS.AF</c></summary>
		AF = 0x00000008,
		/// <summary><c>RFLAGS.CF</c></summary>
		CF = 0x00000010,
		/// <summary><c>RFLAGS.PF</c></summary>
		PF = 0x00000020,
		/// <summary><c>RFLAGS.DF</c></summary>
		DF = 0x00000040,
		/// <summary><c>RFLAGS.IF</c></summary>
		IF = 0x00000080,
		/// <summary><c>RFLAGS.AC</c></summary>
		AC = 0x00000100,
		/// <summary><c>UIF</c></summary>
		UIF = 0x00000200,
		/// <summary>FPU status word bit <c>C0</c></summary>
		C0 = 0x00000400,
		/// <summary>FPU status word bit <c>C1</c></summary>
		C1 = 0x00000800,
		/// <summary>FPU status word bit <c>C2</c></summary>
		C2 = 0x00001000,
		/// <summary>FPU status word bit <c>C3</c></summary>
		C3 = 0x00002000
	};
	DEFINE_FLAGS(RflagsBits)
		DEFINE_COMP(RflagsBits)
		DEFINE_ARITH(RflagsBits)

}
