// C# helper headers
#include <csharp/classes.h>
#include <csharp/enum.h>



// Commonly used headers
#include <cstdint>
#include <format>
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#pragma once

// Code generated from Iced. Do not edit.
// Commit tag: badb6147c0994a4954fa27645aba2b02c2bb9502.
// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors
// ⚠️This file was generated by GENERATOR!🦹‍♂️
namespace Iced::Intel
{
	/// <summary>Tuple type (EVEX/MVEX) which can be used to get the disp8 scale factor <c>N</c></summary>
	enum class TupleType
	{
		/// <summary><c>N = 1</c></summary>
		N1 = 0,
		/// <summary><c>N = 2</c></summary>
		N2 = 1,
		/// <summary><c>N = 4</c></summary>
		N4 = 2,
		/// <summary><c>N = 8</c></summary>
		N8 = 3,
		/// <summary><c>N = 16</c></summary>
		N16 = 4,
		/// <summary><c>N = 32</c></summary>
		N32 = 5,
		/// <summary><c>N = 64</c></summary>
		N64 = 6,
		/// <summary><c>N = b ? 4 : 8</c></summary>
		N8b4 = 7,
		/// <summary><c>N = b ? 4 : 16</c></summary>
		N16b4 = 8,
		/// <summary><c>N = b ? 4 : 32</c></summary>
		N32b4 = 9,
		/// <summary><c>N = b ? 4 : 64</c></summary>
		N64b4 = 10,
		/// <summary><c>N = b ? 8 : 16</c></summary>
		N16b8 = 11,
		/// <summary><c>N = b ? 8 : 32</c></summary>
		N32b8 = 12,
		/// <summary><c>N = b ? 8 : 64</c></summary>
		N64b8 = 13,
		/// <summary><c>N = b ? 2 : 4</c></summary>
		N4b2 = 14,
		/// <summary><c>N = b ? 2 : 8</c></summary>
		N8b2 = 15,
		/// <summary><c>N = b ? 2 : 16</c></summary>
		N16b2 = 16,
		/// <summary><c>N = b ? 2 : 32</c></summary>
		N32b2 = 17,
		/// <summary><c>N = b ? 2 : 64</c></summary>
		N64b2 = 18
	};

	DEFINE_COMP(TupleType)
		DEFINE_ARITH(TupleType)

}
